export type Provider = {
  id: string;
  name: string;
  title: { ro: string; ru: string; en: string };
  category: string;
  city: string;
  rating: number;
  reviewCount: number;
  priceFrom: number;
  currency: string;
  nextSlot: string;
  verified: true;
  avatar: string;
  cover: string;
  bio: { ro: string; ru: string; en: string };
  tags: string[];
  aiScore: number;
  scores: {
    reviews: number;
    profile: number;
    response: number;
    experience: number;
    complaints: number;
  };
};

const portraits = [
  "https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=400&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=400&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=400&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&q=80&auto=format&fit=crop",
];

const covers = [
  "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1600&q=80&auto=format&fit=crop",
];

export const providers: Provider[] = [
  // ─── 100 NEW PROVIDERS ────────────────────────────────────────────────────────
  // Append these entries inside the `providers` array in your existing file.
  // All image URLs cycle through the same portraits[] / covers[] arrays already
  // defined in your file (indices 0-11 for portraits, 0-2 for covers).

  // ── AUTO ──────────────────────────────────────────────────────────────────
  {
    id: "ion-chiriac",
    name: "Ion Chiriac",
    title: {
      ro: "Specialist vopsitorie auto",
      ru: "Специалист по покраске авто",
      en: "Auto body & paint specialist",
    },
    category: "auto",
    city: "Chișinău, Ciocana",
    rating: 4.7,
    reviewCount: 143,
    priceFrom: 1200,
    currency: "MDL",
    nextSlot: "Joi, 10:00",
    verified: true,
    avatar: portraits[10],
    cover: covers[1],
    bio: {
      ro: "Vopsitorie și caroserie, 10 ani experiență.",
      ru: "Кузовной ремонт и покраска, 10 лет опыта.",
      en: "Bodywork & painting, 10 years experience.",
    },
    tags: ["Vopsitorie", "Caroserie"],
    aiScore: 89,
    scores: { reviews: 26, profile: 18, response: 17, experience: 9, complaints: 19 },
  },
  {
    id: "petru-gavrilov",
    name: "Petru Gavrilov",
    title: { ro: "Tehnician anvelope & jante", ru: "Шиномонтажник", en: "Tyre & wheel technician" },
    category: "auto",
    city: "Chișinău, Buiucani",
    rating: 4.6,
    reviewCount: 312,
    priceFrom: 180,
    currency: "MDL",
    nextSlot: "Astăzi, 15:00",
    verified: true,
    avatar: portraits[1],
    cover: covers[2],
    bio: {
      ro: "Schimb anvelope sezonier, echilibrare, geometrie.",
      ru: "Сезонная замена, балансировка, развал-схождение.",
      en: "Seasonal swap, balancing, wheel alignment.",
    },
    tags: ["Anvelope", "Geometrie"],
    aiScore: 87,
    scores: { reviews: 25, profile: 18, response: 19, experience: 8, complaints: 17 },
  },
  {
    id: "gheorghe-olaru",
    name: "Gheorghe Olaru",
    title: {
      ro: "Specialist climatizare auto",
      ru: "Специалист автокондиционеров",
      en: "Auto A/C specialist",
    },
    category: "auto",
    city: "Chișinău, Râșcani",
    rating: 4.8,
    reviewCount: 97,
    priceFrom: 400,
    currency: "MDL",
    nextSlot: "Mâine, 11:00",
    verified: true,
    avatar: portraits[4],
    cover: covers[0],
    bio: {
      ro: "Reîncărcare freon, reparații compresor AC.",
      ru: "Заправка фреоном, ремонт компрессора.",
      en: "Refrigerant recharge, compressor repair.",
    },
    tags: ["AC", "Freon"],
    aiScore: 91,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "dmitri-vataman",
    name: "Dmitri Vataman",
    title: { ro: "Electrician auto", ru: "Автоэлектрик", en: "Auto electrician" },
    category: "auto",
    city: "Chișinău, Botanica",
    rating: 4.7,
    reviewCount: 175,
    priceFrom: 300,
    currency: "MDL",
    nextSlot: "Joi, 09:00",
    verified: true,
    avatar: portraits[6],
    cover: covers[1],
    bio: {
      ro: "Diagnoză, instalare alarme, sisteme audio.",
      ru: "Диагностика, сигнализации, аудиосистемы.",
      en: "Diagnostics, alarms, audio systems.",
    },
    tags: ["Diagnoză", "Alarme"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "artur-bostan",
    name: "Artur Bostan",
    title: {
      ro: "Detailing auto profesionist",
      ru: "Профессиональный детейлинг",
      en: "Professional auto detailing",
    },
    category: "auto",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 88,
    priceFrom: 800,
    currency: "MDL",
    nextSlot: "Sâmbătă, 10:00",
    verified: true,
    avatar: portraits[11],
    cover: covers[2],
    bio: {
      ro: "Polish, ceramică, folie protecție vopsea.",
      ru: "Полировка, керамика, защитная плёнка.",
      en: "Polish, ceramic coating, PPF.",
    },
    tags: ["Detailing", "Ceramică"],
    aiScore: 94,
    scores: { reviews: 28, profile: 20, response: 19, experience: 9, complaints: 18 },
  },

  // ── HEALTH ────────────────────────────────────────────────────────────────
  {
    id: "stefan-mihai",
    name: "Dr. Ștefan Mihai",
    title: { ro: "Cardiolog", ru: "Кардиолог", en: "Cardiologist" },
    category: "health",
    city: "Chișinău, Râșcani",
    rating: 4.9,
    reviewCount: 305,
    priceFrom: 1200,
    currency: "MDL",
    nextSlot: "Miercuri, 09:00",
    verified: true,
    avatar: portraits[11],
    cover: covers[0],
    bio: {
      ro: "EKG, ecografie cardiacă, consultații.",
      ru: "ЭКГ, УЗИ сердца, консультации.",
      en: "ECG, cardiac ultrasound, consultations.",
    },
    tags: ["Inimă", "EKG"],
    aiScore: 96,
    scores: { reviews: 29, profile: 20, response: 19, experience: 10, complaints: 18 },
  },
  {
    id: "natalia-vrabie",
    name: "Dr. Natalia Vrabie",
    title: { ro: "Dermatolog", ru: "Дерматолог", en: "Dermatologist" },
    category: "health",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 224,
    priceFrom: 900,
    currency: "MDL",
    nextSlot: "Vineri, 11:00",
    verified: true,
    avatar: portraits[3],
    cover: covers[1],
    bio: {
      ro: "Tratamente acnee, dermatoscopie, alunițe.",
      ru: "Лечение акне, дерматоскопия, родинки.",
      en: "Acne treatment, dermoscopy, moles.",
    },
    tags: ["Acnee", "Dermatoscopie"],
    aiScore: 93,
    scores: { reviews: 28, profile: 19, response: 18, experience: 9, complaints: 19 },
  },
  {
    id: "andrei-frunza",
    name: "Dr. Andrei Frîncu",
    title: { ro: "Ortoped-traumatolog", ru: "Ортопед-травматолог", en: "Orthopaedic surgeon" },
    category: "health",
    city: "Chișinău, Botanica",
    rating: 4.9,
    reviewCount: 178,
    priceFrom: 1100,
    currency: "MDL",
    nextSlot: "Luni, 08:30",
    verified: true,
    avatar: portraits[0],
    cover: covers[2],
    bio: {
      ro: "Coloane, genunchi, reabilitare post-operatorie.",
      ru: "Позвоночник, колени, послеоперационная реабилитация.",
      en: "Spine, knees, post-op rehabilitation.",
    },
    tags: ["Ortopedie", "Genunchi"],
    aiScore: 95,
    scores: { reviews: 29, profile: 20, response: 18, experience: 10, complaints: 18 },
  },
  {
    id: "luminita-popa",
    name: "Dr. Luminița Popa",
    title: { ro: "Psihiatru", ru: "Психиатр", en: "Psychiatrist" },
    category: "health",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 141,
    priceFrom: 1300,
    currency: "MDL",
    nextSlot: "Marți, 10:00",
    verified: true,
    avatar: portraits[2],
    cover: covers[0],
    bio: {
      ro: "Anxietate, depresie, tulburări somn.",
      ru: "Тревога, депрессия, нарушения сна.",
      en: "Anxiety, depression, sleep disorders.",
    },
    tags: ["Anxietate", "Depresie"],
    aiScore: 92,
    scores: { reviews: 28, profile: 19, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "igor-botnaru",
    name: "Dr. Igor Botnaru",
    title: { ro: "Medic de familie", ru: "Семейный врач", en: "Family doctor" },
    category: "health",
    city: "Chișinău, Buiucani",
    rating: 4.7,
    reviewCount: 430,
    priceFrom: 600,
    currency: "MDL",
    nextSlot: "Astăzi, 14:00",
    verified: true,
    avatar: portraits[5],
    cover: covers[1],
    bio: {
      ro: "Consultații generale, analize, rețete.",
      ru: "Общие консультации, анализы, рецепты.",
      en: "General consultations, tests, prescriptions.",
    },
    tags: ["Familie", "Consultații"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 19, experience: 9, complaints: 17 },
  },
  {
    id: "corina-ciobanu",
    name: "Dr. Corina Ciobanu",
    title: { ro: "Oftalmolog", ru: "Офтальмолог", en: "Ophthalmologist" },
    category: "health",
    city: "Chișinău, Râșcani",
    rating: 4.8,
    reviewCount: 196,
    priceFrom: 850,
    currency: "MDL",
    nextSlot: "Joi, 13:00",
    verified: true,
    avatar: portraits[8],
    cover: covers[2],
    bio: {
      ro: "Vederea, lentile de contact, laser LASIK.",
      ru: "Зрение, контактные линзы, лазер LASIK.",
      en: "Vision, contact lenses, LASIK laser.",
    },
    tags: ["Ochi", "LASIK"],
    aiScore: 93,
    scores: { reviews: 28, profile: 19, response: 19, experience: 9, complaints: 18 },
  },

  // ── HOME ─────────────────────────────────────────────────────────────────
  {
    id: "vasile-cebanu",
    name: "Vasile Cebanu",
    title: { ro: "Instalator sanitar", ru: "Сантехник", en: "Plumber" },
    category: "home",
    city: "Chișinău, Buiucani",
    rating: 4.6,
    reviewCount: 198,
    priceFrom: 200,
    currency: "MDL",
    nextSlot: "Astăzi, 19:00",
    verified: true,
    avatar: portraits[0],
    cover: covers[2],
    bio: {
      ro: "Instalații sanitare și termoficare.",
      ru: "Сантехника и отопление.",
      en: "Plumbing & heating systems.",
    },
    tags: ["Urgență", "Instalații"],
    aiScore: 88,
    scores: { reviews: 26, profile: 17, response: 20, experience: 8, complaints: 17 },
  },
  {
    id: "mihai-spataru",
    name: "Mihai Spătaru",
    title: { ro: "Zugrav-decorator", ru: "Маляр-декоратор", en: "Painter & decorator" },
    category: "home",
    city: "Chișinău, Botanica",
    rating: 4.7,
    reviewCount: 267,
    priceFrom: 180,
    currency: "MDL",
    nextSlot: "Mâine, 08:00",
    verified: true,
    avatar: portraits[6],
    cover: covers[0],
    bio: {
      ro: "Vopsit, glet, tapet, decorațiuni interioare.",
      ru: "Покраска, шпаклёвка, обои, декор интерьера.",
      en: "Painting, plastering, wallpaper, interior deco.",
    },
    tags: ["Zugrăvit", "Tapet"],
    aiScore: 87,
    scores: { reviews: 26, profile: 17, response: 18, experience: 8, complaints: 18 },
  },
  {
    id: "tudor-grosu",
    name: "Tudor Grosu",
    title: { ro: "Tâmplar mobilier", ru: "Столяр-мебельщик", en: "Furniture carpenter" },
    category: "home",
    city: "Chișinău, Ciocana",
    rating: 4.8,
    reviewCount: 134,
    priceFrom: 300,
    currency: "MDL",
    nextSlot: "Marți, 09:00",
    verified: true,
    avatar: portraits[10],
    cover: covers[1],
    bio: {
      ro: "Mobilier la comandă, montaj, reparații.",
      ru: "Мебель на заказ, сборка, ремонт.",
      en: "Custom furniture, assembly, repairs.",
    },
    tags: ["Mobilier", "La comandă"],
    aiScore: 91,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "corneliu-lazar",
    name: "Corneliu Lazăr",
    title: {
      ro: "Specialist geamuri termopane",
      ru: "Специалист по окнам ПВХ",
      en: "PVC windows specialist",
    },
    category: "home",
    city: "Chișinău, Centru",
    rating: 4.6,
    reviewCount: 209,
    priceFrom: 250,
    currency: "MDL",
    nextSlot: "Joi, 10:00",
    verified: true,
    avatar: portraits[1],
    cover: covers[2],
    bio: {
      ro: "Montaj, reglaj și reparații termopane.",
      ru: "Монтаж, регулировка и ремонт окон ПВХ.",
      en: "Installation, adjustment & PVC window repair.",
    },
    tags: ["Termopane", "Montaj"],
    aiScore: 86,
    scores: { reviews: 25, profile: 17, response: 18, experience: 8, complaints: 18 },
  },
  {
    id: "oleg-busuioc",
    name: "Oleg Busuioc",
    title: { ro: "Faianțar & parchetar", ru: "Плиточник и паркетчик", en: "Tiler & floor layer" },
    category: "home",
    city: "Chișinău, Râșcani",
    rating: 4.8,
    reviewCount: 181,
    priceFrom: 220,
    currency: "MDL",
    nextSlot: "Mâine, 07:30",
    verified: true,
    avatar: portraits[4],
    cover: covers[0],
    bio: {
      ro: "Gresie, faianță, parchet, laminat.",
      ru: "Кафель, плитка, паркет, ламинат.",
      en: "Tiles, ceramics, parquet, laminate.",
    },
    tags: ["Faianță", "Parchet"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 18, experience: 9, complaints: 18 },
  },

  // ── LEGAL ────────────────────────────────────────────────────────────────
  {
    id: "vadim-cucos",
    name: "Vadim Cucoș",
    title: { ro: "Avocat penal", ru: "Адвокат по уголовным делам", en: "Criminal defense lawyer" },
    category: "legal",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 62,
    priceFrom: 2000,
    currency: "MDL",
    nextSlot: "Luni, 09:00",
    verified: true,
    avatar: portraits[5],
    cover: covers[1],
    bio: {
      ro: "Apărare penală, dosare complexe.",
      ru: "Уголовная защита, сложные дела.",
      en: "Criminal defense, complex cases.",
    },
    tags: ["Penal", "Apărare"],
    aiScore: 95,
    scores: { reviews: 29, profile: 20, response: 18, experience: 10, complaints: 18 },
  },
  {
    id: "rodica-lungu",
    name: "Rodica Lungu",
    title: { ro: "Notar public", ru: "Нотариус", en: "Public notary" },
    category: "legal",
    city: "Chișinău, Buiucani",
    rating: 4.8,
    reviewCount: 540,
    priceFrom: 500,
    currency: "MDL",
    nextSlot: "Astăzi, 13:00",
    verified: true,
    avatar: portraits[7],
    cover: covers[2],
    bio: {
      ro: "Acte notariale, succesiuni, procuri.",
      ru: "Нотариальные акты, наследство, доверенности.",
      en: "Notarial deeds, inheritance, powers of attorney.",
    },
    tags: ["Notar", "Succesiuni"],
    aiScore: 92,
    scores: { reviews: 28, profile: 19, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "vlad-railean",
    name: "Vlad Railean",
    title: { ro: "Jurist imobiliar", ru: "Юрист по недвижимости", en: "Real estate lawyer" },
    category: "legal",
    city: "Chișinău, Centru",
    rating: 4.7,
    reviewCount: 119,
    priceFrom: 1200,
    currency: "MDL",
    nextSlot: "Marți, 11:00",
    verified: true,
    avatar: portraits[11],
    cover: covers[0],
    bio: {
      ro: "Tranzacții imobiliare, verificare acte.",
      ru: "Сделки с недвижимостью, проверка документов.",
      en: "Property transactions, document verification.",
    },
    tags: ["Imobiliar", "Contracte"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "svetlana-moraru",
    name: "Svetlana Moraru",
    title: {
      ro: "Avocat familie & divorț",
      ru: "Семейный адвокат и развод",
      en: "Family & divorce lawyer",
    },
    category: "legal",
    city: "Chișinău, Botanica",
    rating: 4.8,
    reviewCount: 94,
    priceFrom: 1400,
    currency: "MDL",
    nextSlot: "Miercuri, 10:00",
    verified: true,
    avatar: portraits[9],
    cover: covers[1],
    bio: {
      ro: "Divorț, custodie copii, pensie alimentară.",
      ru: "Развод, опека, алименты.",
      en: "Divorce, child custody, alimony.",
    },
    tags: ["Familie", "Divorț"],
    aiScore: 91,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 18 },
  },

  // ── IT ───────────────────────────────────────────────────────────────────
  {
    id: "nicoleta-grama",
    name: "Nicoleta Grama",
    title: { ro: "UI/UX Designer", ru: "UI/UX дизайнер", en: "UI/UX Designer" },
    category: "it",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 97,
    priceFrom: 550,
    currency: "MDL",
    nextSlot: "Mâine, 11:00",
    verified: true,
    avatar: portraits[7],
    cover: covers[1],
    bio: {
      ro: "Figma, design sisteme, prototipuri.",
      ru: "Figma, дизайн-системы, прототипы.",
      en: "Figma, design systems, prototypes.",
    },
    tags: ["Figma", "UX"],
    aiScore: 94,
    scores: { reviews: 28, profile: 20, response: 18, experience: 9, complaints: 19 },
  },
  {
    id: "eugen-railean",
    name: "Eugen Railean",
    title: { ro: "DevOps engineer", ru: "DevOps инженер", en: "DevOps engineer" },
    category: "it",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 58,
    priceFrom: 900,
    currency: "MDL",
    nextSlot: "Mâine, 14:00",
    verified: true,
    avatar: portraits[10],
    cover: covers[2],
    bio: {
      ro: "Docker, Kubernetes, CI/CD pipelines.",
      ru: "Docker, Kubernetes, CI/CD.",
      en: "Docker, Kubernetes, CI/CD pipelines.",
    },
    tags: ["DevOps", "Docker"],
    aiScore: 96,
    scores: { reviews: 29, profile: 20, response: 19, experience: 10, complaints: 18 },
  },
  {
    id: "diana-condrea",
    name: "Diana Condrea",
    title: {
      ro: "Specialist SEO & marketing digital",
      ru: "SEO специалист",
      en: "SEO & digital marketing",
    },
    category: "it",
    city: "Chișinău, Buiucani",
    rating: 4.7,
    reviewCount: 113,
    priceFrom: 500,
    currency: "MDL",
    nextSlot: "Joi, 10:00",
    verified: true,
    avatar: portraits[4],
    cover: covers[0],
    bio: {
      ro: "SEO on-page, Google Ads, analiză web.",
      ru: "SEO, Google Ads, веб-аналитика.",
      en: "On-page SEO, Google Ads, web analytics.",
    },
    tags: ["SEO", "Google Ads"],
    aiScore: 89,
    scores: { reviews: 26, profile: 18, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "radu-condurache",
    name: "Radu Condurache",
    title: {
      ro: "Specialist cybersecurity",
      ru: "Специалист по кибербезопасности",
      en: "Cybersecurity specialist",
    },
    category: "it",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 44,
    priceFrom: 1200,
    currency: "MDL",
    nextSlot: "Miercuri, 15:00",
    verified: true,
    avatar: portraits[5],
    cover: covers[1],
    bio: {
      ro: "Audit securitate, penetration testing.",
      ru: "Аудит безопасности, тестирование на проникновение.",
      en: "Security audits, penetration testing.",
    },
    tags: ["Securitate", "Pentest"],
    aiScore: 97,
    scores: { reviews: 29, profile: 20, response: 20, experience: 10, complaints: 18 },
  },
  {
    id: "ana-savca",
    name: "Ana Savca",
    title: { ro: "Data scientist", ru: "Специалист по данным", en: "Data scientist" },
    category: "it",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 37,
    priceFrom: 1000,
    currency: "MDL",
    nextSlot: "Vineri, 11:00",
    verified: true,
    avatar: portraits[8],
    cover: covers[2],
    bio: {
      ro: "Python, ML, dashboard-uri Power BI.",
      ru: "Python, ML, дашборды Power BI.",
      en: "Python, ML, Power BI dashboards.",
    },
    tags: ["Python", "ML"],
    aiScore: 95,
    scores: { reviews: 28, profile: 20, response: 19, experience: 10, complaints: 18 },
  },

  // ── FITNESS ──────────────────────────────────────────────────────────────
  {
    id: "lidia-petrov",
    name: "Lidia Petrov",
    title: { ro: "Instructor yoga", ru: "Инструктор йоги", en: "Yoga instructor" },
    category: "fitness",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 167,
    priceFrom: 250,
    currency: "MDL",
    nextSlot: "Mâine, 08:00",
    verified: true,
    avatar: portraits[9],
    cover: covers[2],
    bio: {
      ro: "Hatha, vinyasa și meditație.",
      ru: "Хатха, виньяса и медитация.",
      en: "Hatha, vinyasa & meditation.",
    },
    tags: ["Yoga", "Meditație"],
    aiScore: 91,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "marius-ciobanu",
    name: "Marius Ciobanu",
    title: {
      ro: "Antrenor box & kickbox",
      ru: "Тренер бокса и кикбокса",
      en: "Boxing & kickboxing coach",
    },
    category: "fitness",
    city: "Chișinău, Botanica",
    rating: 4.7,
    reviewCount: 143,
    priceFrom: 280,
    currency: "MDL",
    nextSlot: "Marți, 18:00",
    verified: true,
    avatar: portraits[6],
    cover: covers[0],
    bio: {
      ro: "Antrenamente individuale și de grup.",
      ru: "Индивидуальные и групповые тренировки.",
      en: "Individual & group training sessions.",
    },
    tags: ["Box", "Kickbox"],
    aiScore: 89,
    scores: { reviews: 26, profile: 18, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "angela-lupu",
    name: "Angela Lupu",
    title: { ro: "Instructor pilates", ru: "Инструктор пилатеса", en: "Pilates instructor" },
    category: "fitness",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 128,
    priceFrom: 270,
    currency: "MDL",
    nextSlot: "Joi, 09:00",
    verified: true,
    avatar: portraits[3],
    cover: covers[1],
    bio: {
      ro: "Pilates mat și reformer, postura, core.",
      ru: "Мат и реформер пилатес, осанка, кор.",
      en: "Mat & reformer pilates, posture, core.",
    },
    tags: ["Pilates", "Core"],
    aiScore: 93,
    scores: { reviews: 28, profile: 19, response: 19, experience: 9, complaints: 18 },
  },
  {
    id: "sergiu-calancea",
    name: "Sergiu Calanceа",
    title: {
      ro: "Antrenor atletism & alergare",
      ru: "Тренер по лёгкой атлетике",
      en: "Athletics & running coach",
    },
    category: "fitness",
    city: "Chișinău, Râșcani",
    rating: 4.7,
    reviewCount: 76,
    priceFrom: 220,
    currency: "MDL",
    nextSlot: "Sâmbătă, 07:00",
    verified: true,
    avatar: portraits[0],
    cover: covers[2],
    bio: {
      ro: "Pregătire maraton, plan alergare personalizat.",
      ru: "Подготовка к марафону, персональный план бега.",
      en: "Marathon prep, personalized running plans.",
    },
    tags: ["Alergare", "Maraton"],
    aiScore: 88,
    scores: { reviews: 26, profile: 18, response: 17, experience: 9, complaints: 18 },
  },

  // ── BEAUTY ───────────────────────────────────────────────────────────────
  {
    id: "tatiana-botnaru",
    name: "Tatiana Botnaru",
    title: { ro: "Coafor & stilist", ru: "Парикмахер & стилист", en: "Hair stylist" },
    category: "beauty",
    city: "Chișinău, Buiucani",
    rating: 4.7,
    reviewCount: 254,
    priceFrom: 350,
    currency: "MDL",
    nextSlot: "Sâmbătă, 10:00",
    verified: true,
    avatar: portraits[2],
    cover: covers[1],
    bio: {
      ro: "Tuns, colorare și tratamente păr.",
      ru: "Стрижка, окраска и уход за волосами.",
      en: "Cuts, coloring & hair treatments.",
    },
    tags: ["Colorare", "Keratin"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "aliona-danu",
    name: "Aliona Danu",
    title: { ro: "Cosmetician facial", ru: "Косметолог", en: "Facial cosmetologist" },
    category: "beauty",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 192,
    priceFrom: 450,
    currency: "MDL",
    nextSlot: "Vineri, 13:00",
    verified: true,
    avatar: portraits[4],
    cover: covers[0],
    bio: {
      ro: "Curățare facială, tratamente anti-aging.",
      ru: "Чистка лица, антивозрастные процедуры.",
      en: "Facial cleansing, anti-aging treatments.",
    },
    tags: ["Facial", "Anti-aging"],
    aiScore: 92,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 19 },
  },
  {
    id: "veronica-stanciu",
    name: "Veronica Stanciu",
    title: {
      ro: "Specialist unghii gel & acryl",
      ru: "Мастер гелевых и акриловых ногтей",
      en: "Gel & acrylic nail artist",
    },
    category: "beauty",
    city: "Chișinău, Botanica",
    rating: 4.9,
    reviewCount: 388,
    priceFrom: 300,
    currency: "MDL",
    nextSlot: "Mâine, 12:00",
    verified: true,
    avatar: portraits[7],
    cover: covers[2],
    bio: {
      ro: "Manichiură, unghii gel, nail art.",
      ru: "Маникюр, гель-ногти, нейл-арт.",
      en: "Manicure, gel nails, nail art.",
    },
    tags: ["Gel", "Nail Art"],
    aiScore: 94,
    scores: { reviews: 29, profile: 20, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "mariana-scutaru",
    name: "Mariana Scutaru",
    title: {
      ro: "Specialist sprâncene & gene",
      ru: "Мастер бровей и ресниц",
      en: "Brow & lash specialist",
    },
    category: "beauty",
    city: "Chișinău, Râșcani",
    rating: 4.8,
    reviewCount: 215,
    priceFrom: 250,
    currency: "MDL",
    nextSlot: "Joi, 11:00",
    verified: true,
    avatar: portraits[9],
    cover: covers[0],
    bio: {
      ro: "Microblading, laminare, extensii gene.",
      ru: "Микроблейдинг, ламинирование, наращивание ресниц.",
      en: "Microblading, lamination, lash extensions.",
    },
    tags: ["Microblading", "Gene"],
    aiScore: 93,
    scores: { reviews: 28, profile: 19, response: 19, experience: 9, complaints: 18 },
  },

  // ── EDUCATION ────────────────────────────────────────────────────────────
  {
    id: "oxana-turcan",
    name: "Oxana Turcan",
    title: { ro: "Profesor engleză", ru: "Учитель английского", en: "English teacher" },
    category: "education",
    city: "Chișinău, Botanica",
    rating: 4.9,
    reviewCount: 231,
    priceFrom: 180,
    currency: "MDL",
    nextSlot: "Joi, 17:30",
    verified: true,
    avatar: portraits[3],
    cover: covers[0],
    bio: {
      ro: "IELTS, business English, conversații.",
      ru: "IELTS, бизнес-английский, разговорный.",
      en: "IELTS, business English, conversation.",
    },
    tags: ["IELTS", "Business English"],
    aiScore: 95,
    scores: { reviews: 29, profile: 19, response: 19, experience: 10, complaints: 18 },
  },
  {
    id: "cristian-nistor",
    name: "Cristian Nistor",
    title: {
      ro: "Profesor fizică & chimie",
      ru: "Учитель физики и химии",
      en: "Physics & chemistry tutor",
    },
    category: "education",
    city: "Chișinău, Centru",
    rating: 4.7,
    reviewCount: 104,
    priceFrom: 190,
    currency: "MDL",
    nextSlot: "Marți, 16:00",
    verified: true,
    avatar: portraits[6],
    cover: covers[1],
    bio: {
      ro: "Pregătire BAC fizică, olimpiade chimie.",
      ru: "ЕГЭ физика, олимпиады по химии.",
      en: "Physics BAC prep, chemistry olympiads.",
    },
    tags: ["Fizică", "Chimie"],
    aiScore: 89,
    scores: { reviews: 26, profile: 18, response: 17, experience: 9, complaints: 19 },
  },
  {
    id: "liuba-chiriac",
    name: "Liuba Chiriac",
    title: { ro: "Profesor pian", ru: "Учитель фортепиано", en: "Piano teacher" },
    category: "education",
    city: "Chișinău, Buiucani",
    rating: 4.9,
    reviewCount: 77,
    priceFrom: 220,
    currency: "MDL",
    nextSlot: "Sâmbătă, 11:00",
    verified: true,
    avatar: portraits[2],
    cover: covers[2],
    bio: {
      ro: "Clasic și contemporan, copii și adulți.",
      ru: "Классика и современность, дети и взрослые.",
      en: "Classical & contemporary, children & adults.",
    },
    tags: ["Pian", "Clasic"],
    aiScore: 93,
    scores: { reviews: 28, profile: 19, response: 19, experience: 9, complaints: 18 },
  },
  {
    id: "mihai-borta",
    name: "Mihai Borta",
    title: {
      ro: "Instructor auto categoria B",
      ru: "Автоинструктор категории B",
      en: "Driving instructor cat. B",
    },
    category: "education",
    city: "Chișinău, Ciocana",
    rating: 4.8,
    reviewCount: 349,
    priceFrom: 250,
    currency: "MDL",
    nextSlot: "Luni, 10:00",
    verified: true,
    avatar: portraits[11],
    cover: covers[0],
    bio: {
      ro: "Permis auto, lecții practice, examen.",
      ru: "Водительские права, практика, экзамен.",
      en: "Driving licence, practical lessons, test.",
    },
    tags: ["Șofat", "Permis"],
    aiScore: 91,
    scores: { reviews: 27, profile: 18, response: 19, experience: 9, complaints: 18 },
  },
  {
    id: "elena-palii",
    name: "Elena Palii",
    title: { ro: "Logoped", ru: "Логопед", en: "Speech therapist" },
    category: "education",
    city: "Chișinău, Botanica",
    rating: 4.9,
    reviewCount: 156,
    priceFrom: 300,
    currency: "MDL",
    nextSlot: "Miercuri, 14:00",
    verified: true,
    avatar: portraits[8],
    cover: covers[1],
    bio: {
      ro: "Dislexie, bâlbâială, dezvoltare vorbire copii.",
      ru: "Дислексия, заикание, развитие речи у детей.",
      en: "Dyslexia, stuttering, children's speech development.",
    },
    tags: ["Logoped", "Copii"],
    aiScore: 95,
    scores: { reviews: 29, profile: 20, response: 18, experience: 10, complaints: 18 },
  },

  // ── FINANCE ──────────────────────────────────────────────────────────────
  {
    id: "bogdan-harea",
    name: "Bogdan Harea",
    title: { ro: "Contabil autorizat", ru: "Аттестованный бухгалтер", en: "Certified accountant" },
    category: "finance",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 198,
    priceFrom: 800,
    currency: "MDL",
    nextSlot: "Luni, 09:00",
    verified: true,
    avatar: portraits[5],
    cover: covers[2],
    bio: {
      ro: "Contabilitate SRL, raportări fiscale, 1C.",
      ru: "Бухучёт ООО, налоговая отчётность, 1С.",
      en: "LLC accounting, tax filings, 1C.",
    },
    tags: ["Contabilitate", "Fiscal"],
    aiScore: 92,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 19 },
  },
  {
    id: "irina-ghelbert",
    name: "Irina Ghelbert",
    title: { ro: "Broker credite ipotecare", ru: "Ипотечный брокер", en: "Mortgage broker" },
    category: "finance",
    city: "Chișinău, Râșcani",
    rating: 4.7,
    reviewCount: 83,
    priceFrom: 600,
    currency: "MDL",
    nextSlot: "Marți, 13:00",
    verified: true,
    avatar: portraits[1],
    cover: covers[0],
    bio: {
      ro: "Credite ipotecare, refinanțare, comparare bănci.",
      ru: "Ипотека, рефинансирование, сравнение банков.",
      en: "Mortgages, refinancing, bank comparison.",
    },
    tags: ["Ipotecă", "Credit"],
    aiScore: 89,
    scores: { reviews: 26, profile: 18, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "valentina-savin",
    name: "Valentina Savin",
    title: { ro: "Planificator financiar", ru: "Финансовый планировщик", en: "Financial planner" },
    category: "finance",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 55,
    priceFrom: 900,
    currency: "MDL",
    nextSlot: "Joi, 14:00",
    verified: true,
    avatar: portraits[7],
    cover: covers[1],
    bio: {
      ro: "Buget personal, fond urgență, pensie privată.",
      ru: "Личный бюджет, резервный фонд, частная пенсия.",
      en: "Personal budget, emergency fund, private pension.",
    },
    tags: ["Planificare", "Pensie"],
    aiScore: 94,
    scores: { reviews: 28, profile: 20, response: 19, experience: 9, complaints: 18 },
  },

  // ── EVENTS (new) ─────────────────────────────────────────────────────────
  {
    id: "radu-pintea",
    name: "Radu Pintea",
    title: { ro: "Organizator evenimente", ru: "Организатор мероприятий", en: "Event planner" },
    category: "events",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 112,
    priceFrom: 2000,
    currency: "MDL",
    nextSlot: "Luni, 14:00",
    verified: true,
    avatar: portraits[6],
    cover: covers[0],
    bio: {
      ro: "Nunți, corporate și petreceri private.",
      ru: "Свадьбы, корпоративы, частные вечеринки.",
      en: "Weddings, corporate & private parties.",
    },
    tags: ["Nunți", "Corporate"],
    aiScore: 94,
    scores: { reviews: 28, profile: 20, response: 18, experience: 10, complaints: 18 },
  },
  {
    id: "olga-danila",
    name: "Olga Dănilă",
    title: { ro: "DJ & animatoare", ru: "DJ и аниматор", en: "DJ & event host" },
    category: "events",
    city: "Chișinău, Buiucani",
    rating: 4.8,
    reviewCount: 167,
    priceFrom: 1800,
    currency: "MDL",
    nextSlot: "Sâmbătă, 20:00",
    verified: true,
    avatar: portraits[4],
    cover: covers[2],
    bio: {
      ro: "Muzică live, MC nunți, petreceri corporate.",
      ru: "Живая музыка, MC, корпоративы.",
      en: "Live music, MC weddings, corporate events.",
    },
    tags: ["DJ", "MC"],
    aiScore: 91,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "dorel-carp",
    name: "Dorel Carp",
    title: {
      ro: "Fotograf nuntă & botez",
      ru: "Фотограф свадьбы и крестин",
      en: "Wedding & baptism photographer",
    },
    category: "events",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 204,
    priceFrom: 3000,
    currency: "MDL",
    nextSlot: "Duminică, 10:00",
    verified: true,
    avatar: portraits[0],
    cover: covers[1],
    bio: {
      ro: "Reportaj foto complet, editare inclusă.",
      ru: "Полный фоторепортаж, редактирование включено.",
      en: "Full photo coverage, editing included.",
    },
    tags: ["Nuntă", "Botez"],
    aiScore: 96,
    scores: { reviews: 29, profile: 20, response: 19, experience: 10, complaints: 18 },
  },
  {
    id: "cristina-bulat",
    name: "Cristina Bulat",
    title: { ro: "Decorator floral", ru: "Флорист-декоратор", en: "Floral decorator" },
    category: "events",
    city: "Chișinău, Botanica",
    rating: 4.8,
    reviewCount: 139,
    priceFrom: 1500,
    currency: "MDL",
    nextSlot: "Vineri, 09:00",
    verified: true,
    avatar: portraits[3],
    cover: covers[0],
    bio: {
      ro: "Aranjamente florale nunți, birouri, evenimente.",
      ru: "Цветочные аранжировки для свадеб и мероприятий.",
      en: "Floral arrangements for weddings & events.",
    },
    tags: ["Flori", "Decorații"],
    aiScore: 92,
    scores: { reviews: 28, profile: 19, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "roman-galusca",
    name: "Roman Galușcă",
    title: {
      ro: "Videograf profesionist",
      ru: "Профессиональный видеограф",
      en: "Professional videographer",
    },
    category: "events",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 97,
    priceFrom: 3500,
    currency: "MDL",
    nextSlot: "Sâmbătă, 09:00",
    verified: true,
    avatar: portraits[10],
    cover: covers[2],
    bio: {
      ro: "Film nuntă cinematic, drone, 4K.",
      ru: "Кинематографический свадебный фильм, дрон, 4K.",
      en: "Cinematic wedding film, drone, 4K.",
    },
    tags: ["Video", "Drone"],
    aiScore: 95,
    scores: { reviews: 29, profile: 20, response: 18, experience: 10, complaints: 18 },
  },

  // ── PETS (new) ───────────────────────────────────────────────────────────
  {
    id: "alina-solomon",
    name: "Alina Solomon",
    title: { ro: "Medic veterinar", ru: "Ветеринар", en: "Veterinarian" },
    category: "pets",
    city: "Chișinău, Botanica",
    rating: 4.9,
    reviewCount: 189,
    priceFrom: 300,
    currency: "MDL",
    nextSlot: "Astăzi, 16:00",
    verified: true,
    avatar: portraits[4],
    cover: covers[2],
    bio: {
      ro: "Clinică mobilă, vaccinări și urgențe.",
      ru: "Мобильная клиника, вакцинация и скорая.",
      en: "Mobile clinic, vaccinations & emergencies.",
    },
    tags: ["Veterinar", "Urgență"],
    aiScore: 96,
    scores: { reviews: 29, profile: 20, response: 19, experience: 10, complaints: 18 },
  },
  {
    id: "vasile-moroz",
    name: "Vasile Moroz",
    title: { ro: "Dresor câini", ru: "Кинолог-дрессировщик", en: "Dog trainer" },
    category: "pets",
    city: "Chișinău, Râșcani",
    rating: 4.8,
    reviewCount: 143,
    priceFrom: 350,
    currency: "MDL",
    nextSlot: "Sâmbătă, 09:00",
    verified: true,
    avatar: portraits[6],
    cover: covers[0],
    bio: {
      ro: "Dresaj de bază, comportament, agresivitate.",
      ru: "Базовая дрессировка, поведение, агрессия.",
      en: "Basic training, behaviour, aggression.",
    },
    tags: ["Dresaj", "Comportament"],
    aiScore: 92,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 19 },
  },
  {
    id: "elena-cazan",
    name: "Elena Cazan",
    title: {
      ro: "Groomer animale de companie",
      ru: "Грумер для домашних животных",
      en: "Pet groomer",
    },
    category: "pets",
    city: "Chișinău, Centru",
    rating: 4.7,
    reviewCount: 267,
    priceFrom: 200,
    currency: "MDL",
    nextSlot: "Luni, 11:00",
    verified: true,
    avatar: portraits[2],
    cover: covers[1],
    bio: {
      ro: "Tuns, baie, curățare urechi, unghii.",
      ru: "Стрижка, купание, чистка ушей, когти.",
      en: "Haircut, bath, ear cleaning, nail trim.",
    },
    tags: ["Grooming", "Câini"],
    aiScore: 89,
    scores: { reviews: 26, profile: 18, response: 18, experience: 8, complaints: 19 },
  },
  {
    id: "nina-rurac",
    name: "Nina Rurac",
    title: {
      ro: "Pet-sitter & plimbare câini",
      ru: "Пет-ситтер и выгул собак",
      en: "Pet sitter & dog walker",
    },
    category: "pets",
    city: "Chișinău, Buiucani",
    rating: 4.8,
    reviewCount: 312,
    priceFrom: 100,
    currency: "MDL",
    nextSlot: "Astăzi, 17:00",
    verified: true,
    avatar: portraits[9],
    cover: covers[2],
    bio: {
      ro: "Îngrijire acasă sau la mine, plimbări zilnice.",
      ru: "Уход дома или у меня, ежедневные прогулки.",
      en: "Care at home or mine, daily walks.",
    },
    tags: ["Pet-sitter", "Plimbări"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 19, experience: 8, complaints: 18 },
  },

  // ── CLEANING (new) ───────────────────────────────────────────────────────
  {
    id: "nadejda-chirca",
    name: "Nadejda Chirca",
    title: {
      ro: "Servicii curățenie generală",
      ru: "Генеральная уборка",
      en: "General cleaning services",
    },
    category: "cleaning",
    city: "Chișinău, Ciocana",
    rating: 4.7,
    reviewCount: 320,
    priceFrom: 150,
    currency: "MDL",
    nextSlot: "Mâine, 09:00",
    verified: true,
    avatar: portraits[8],
    cover: covers[1],
    bio: {
      ro: "Curățenie generală, după reparație.",
      ru: "Генеральная уборка, после ремонта.",
      en: "General & post-renovation cleaning.",
    },
    tags: ["Generală", "Post-reparație"],
    aiScore: 89,
    scores: { reviews: 27, profile: 18, response: 19, experience: 8, complaints: 17 },
  },
  {
    id: "svetlana-popa",
    name: "Svetlana Popa",
    title: {
      ro: "Curățenie birouri & spații comerciale",
      ru: "Уборка офисов и коммерческих помещений",
      en: "Office & commercial cleaning",
    },
    category: "cleaning",
    city: "Chișinău, Centru",
    rating: 4.6,
    reviewCount: 187,
    priceFrom: 200,
    currency: "MDL",
    nextSlot: "Luni, 07:00",
    verified: true,
    avatar: portraits[1],
    cover: covers[0],
    bio: {
      ro: "Contract lunar, echipamente profesionale.",
      ru: "Ежемесячный договор, профессиональное оборудование.",
      en: "Monthly contract, professional equipment.",
    },
    tags: ["Birouri", "Contract"],
    aiScore: 86,
    scores: { reviews: 25, profile: 17, response: 18, experience: 8, complaints: 18 },
  },
  {
    id: "anatolie-rosca",
    name: "Anatolie Roșca",
    title: {
      ro: "Curățare chimică canapele & covoare",
      ru: "Химчистка диванов и ковров",
      en: "Sofa & carpet dry cleaning",
    },
    category: "cleaning",
    city: "Chișinău, Botanica",
    rating: 4.8,
    reviewCount: 241,
    priceFrom: 300,
    currency: "MDL",
    nextSlot: "Marți, 10:00",
    verified: true,
    avatar: portraits[5],
    cover: covers[2],
    bio: {
      ro: "Extracție profesională, eliminare pete.",
      ru: "Профессиональная экстракция, удаление пятен.",
      en: "Professional extraction, stain removal.",
    },
    tags: ["Canapele", "Covoare"],
    aiScore: 91,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 18 },
  },

  // ── PHOTOGRAPHY (new) ────────────────────────────────────────────────────
  {
    id: "mihai-ungureanu",
    name: "Mihai Ungureanu",
    title: {
      ro: "Fotograf portret & produs",
      ru: "Фотограф портрет и продукт",
      en: "Portrait & product photographer",
    },
    category: "photography",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 145,
    priceFrom: 1500,
    currency: "MDL",
    nextSlot: "Duminică, 11:00",
    verified: true,
    avatar: portraits[5],
    cover: covers[0],
    bio: {
      ro: "Portret, nuntă și fotografie de produs.",
      ru: "Портрет, свадьба и фото продуктов.",
      en: "Portrait, wedding & product photography.",
    },
    tags: ["Portret", "Produs"],
    aiScore: 93,
    scores: { reviews: 28, profile: 19, response: 18, experience: 10, complaints: 18 },
  },
  {
    id: "iurie-melnic",
    name: "Iurie Melnic",
    title: {
      ro: "Fotograf imobiliar & drone",
      ru: "Фотограф недвижимости и дрон",
      en: "Real estate & drone photographer",
    },
    category: "photography",
    city: "Chișinău, Buiucani",
    rating: 4.7,
    reviewCount: 88,
    priceFrom: 1200,
    currency: "MDL",
    nextSlot: "Joi, 10:00",
    verified: true,
    avatar: portraits[11],
    cover: covers[1],
    bio: {
      ro: "Fotografii imobil, aeriean cu drona.",
      ru: "Фото недвижимости, аэросъёмка.",
      en: "Property photos, aerial drone shots.",
    },
    tags: ["Imobiliar", "Drone"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "lidia-botnari",
    name: "Lidia Botnari",
    title: {
      ro: "Fotograf newborn & familie",
      ru: "Фотограф новорождённых и семей",
      en: "Newborn & family photographer",
    },
    category: "photography",
    city: "Chișinău, Botanica",
    rating: 4.9,
    reviewCount: 176,
    priceFrom: 1800,
    currency: "MDL",
    nextSlot: "Sâmbătă, 09:00",
    verified: true,
    avatar: portraits[7],
    cover: covers[2],
    bio: {
      ro: "Ședințe newborn, maternitate și familie.",
      ru: "Съёмка новорождённых, материнство, семья.",
      en: "Newborn, maternity & family sessions.",
    },
    tags: ["Newborn", "Familie"],
    aiScore: 95,
    scores: { reviews: 29, profile: 20, response: 18, experience: 10, complaints: 18 },
  },

  // ── NUTRITION (new) ──────────────────────────────────────────────────────
  {
    id: "corina-filip",
    name: "Corina Filip",
    title: { ro: "Nutriționist dietetician", ru: "Диетолог", en: "Nutritionist & dietitian" },
    category: "nutrition",
    city: "Chișinău, Râșcani",
    rating: 4.8,
    reviewCount: 94,
    priceFrom: 450,
    currency: "MDL",
    nextSlot: "Vineri, 10:00",
    verified: true,
    avatar: portraits[1],
    cover: covers[2],
    bio: {
      ro: "Planuri alimentare personalizate.",
      ru: "Персональные планы питания.",
      en: "Personalized meal plans.",
    },
    tags: ["Dietă", "Slăbire"],
    aiScore: 92,
    scores: { reviews: 28, profile: 19, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "marina-gutium",
    name: "Marina Gutium",
    title: { ro: "Nutriționist sportiv", ru: "Спортивный диетолог", en: "Sports nutritionist" },
    category: "nutrition",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 72,
    priceFrom: 500,
    currency: "MDL",
    nextSlot: "Marți, 09:00",
    verified: true,
    avatar: portraits[3],
    cover: covers[0],
    bio: {
      ro: "Nutriție pentru performanță, suplimentare.",
      ru: "Питание для спортсменов, добавки.",
      en: "Sports performance nutrition, supplementation.",
    },
    tags: ["Sport", "Performanță"],
    aiScore: 91,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 18 },
  },

  // ── PSYCHOLOGY (new) ─────────────────────────────────────────────────────
  {
    id: "larisa-condrea",
    name: "Larisa Condrea",
    title: { ro: "Psiholog clinician", ru: "Клинический психолог", en: "Clinical psychologist" },
    category: "psychology",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 118,
    priceFrom: 600,
    currency: "MDL",
    nextSlot: "Luni, 12:00",
    verified: true,
    avatar: portraits[9],
    cover: covers[1],
    bio: {
      ro: "Terapie cognitiv-comportamentală, traume.",
      ru: "КПТ, травматерапия.",
      en: "Cognitive behavioural therapy, trauma.",
    },
    tags: ["CBT", "Traume"],
    aiScore: 95,
    scores: { reviews: 29, profile: 20, response: 18, experience: 10, complaints: 18 },
  },
  {
    id: "sergiu-avram",
    name: "Sergiu Avram",
    title: { ro: "Psihoterapeut de cuplu", ru: "Семейный психотерапевт", en: "Couples therapist" },
    category: "psychology",
    city: "Chișinău, Buiucani",
    rating: 4.8,
    reviewCount: 86,
    priceFrom: 700,
    currency: "MDL",
    nextSlot: "Miercuri, 11:00",
    verified: true,
    avatar: portraits[0],
    cover: covers[2],
    bio: {
      ro: "Terapie de cuplu, comunicare, crize relaționale.",
      ru: "Семейная терапия, коммуникация, кризисы.",
      en: "Couple therapy, communication, relational crises.",
    },
    tags: ["Cuplu", "Relații"],
    aiScore: 92,
    scores: { reviews: 28, profile: 19, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "alina-negru",
    name: "Alina Negru",
    title: {
      ro: "Psiholog pentru copii & adolescenți",
      ru: "Психолог для детей и подростков",
      en: "Child & teen psychologist",
    },
    category: "psychology",
    city: "Chișinău, Botanica",
    rating: 4.9,
    reviewCount: 134,
    priceFrom: 550,
    currency: "MDL",
    nextSlot: "Joi, 15:00",
    verified: true,
    avatar: portraits[4],
    cover: covers[0],
    bio: {
      ro: "Anxietate copii, ADHD, adaptare școlară.",
      ru: "Тревожность детей, СДВГ, адаптация.",
      en: "Child anxiety, ADHD, school adaptation.",
    },
    tags: ["Copii", "ADHD"],
    aiScore: 94,
    scores: { reviews: 28, profile: 20, response: 18, experience: 10, complaints: 18 },
  },

  // ── TRANSLATION (new) ────────────────────────────────────────────────────
  {
    id: "lucia-enache",
    name: "Lucia Enache",
    title: { ro: "Traducător RO-EN-RU", ru: "Переводчик РО-АН-РУ", en: "RO-EN-RU translator" },
    category: "translation",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 204,
    priceFrom: 120,
    currency: "MDL",
    nextSlot: "Astăzi, 18:00",
    verified: true,
    avatar: portraits[2],
    cover: covers[1],
    bio: {
      ro: "Traduceri juridice, medicale și tehnice.",
      ru: "Юридические, медицинские и технические переводы.",
      en: "Legal, medical & technical translations.",
    },
    tags: ["Juridic", "Tehnic"],
    aiScore: 93,
    scores: { reviews: 28, profile: 20, response: 19, experience: 9, complaints: 17 },
  },
  {
    id: "tatiana-pascari",
    name: "Tatiana Pașcari",
    title: {
      ro: "Interpret simultan",
      ru: "Синхронный переводчик",
      en: "Simultaneous interpreter",
    },
    category: "translation",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 67,
    priceFrom: 800,
    currency: "MDL",
    nextSlot: "Luni, 10:00",
    verified: true,
    avatar: portraits[7],
    cover: covers[2],
    bio: {
      ro: "Conferințe, RO-EN-FR simultan.",
      ru: "Конференции, РО-АН-ФР синхронно.",
      en: "Conferences, RO-EN-FR simultaneously.",
    },
    tags: ["Simultan", "Conferințe"],
    aiScore: 96,
    scores: { reviews: 29, profile: 20, response: 19, experience: 10, complaints: 18 },
  },

  // ── REAL ESTATE (new) ────────────────────────────────────────────────────
  {
    id: "andrei-gorea",
    name: "Andrei Gorea",
    title: { ro: "Agent imobiliar", ru: "Агент по недвижимости", en: "Real estate agent" },
    category: "realestate",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 278,
    priceFrom: 0,
    currency: "MDL",
    nextSlot: "Astăzi, 15:00",
    verified: true,
    avatar: portraits[10],
    cover: covers[0],
    bio: {
      ro: "Vânzare, cumpărare și închiriere apartamente.",
      ru: "Продажа, покупка и аренда квартир.",
      en: "Apartment sales, purchases & rentals.",
    },
    tags: ["Apartamente", "Vânzare"],
    aiScore: 91,
    scores: { reviews: 27, profile: 19, response: 19, experience: 9, complaints: 17 },
  },
  {
    id: "valentina-bordeianu",
    name: "Valentina Bordeianu",
    title: {
      ro: "Agent imobiliar comercial",
      ru: "Агент по коммерческой недвижимости",
      en: "Commercial real estate agent",
    },
    category: "realestate",
    city: "Chișinău, Botanica",
    rating: 4.7,
    reviewCount: 91,
    priceFrom: 0,
    currency: "MDL",
    nextSlot: "Marți, 10:00",
    verified: true,
    avatar: portraits[3],
    cover: covers[1],
    bio: {
      ro: "Birouri, spații comerciale, depozite.",
      ru: "Офисы, торговые площади, склады.",
      en: "Offices, retail spaces, warehouses.",
    },
    tags: ["Comercial", "Birouri"],
    aiScore: 89,
    scores: { reviews: 26, profile: 18, response: 18, experience: 9, complaints: 18 },
  },

  // ── ACCOUNTING (new) ─────────────────────────────────────────────────────
  {
    id: "ana-mardare",
    name: "Ana Mardare",
    title: {
      ro: "Contabil pentru freelanceri",
      ru: "Бухгалтер для фрилансеров",
      en: "Accountant for freelancers",
    },
    category: "accounting",
    city: "Chișinău, Râșcani",
    rating: 4.8,
    reviewCount: 143,
    priceFrom: 400,
    currency: "MDL",
    nextSlot: "Miercuri, 09:00",
    verified: true,
    avatar: portraits[8],
    cover: covers[2],
    bio: {
      ro: "Declarații PFA, optimizare fiscală, online.",
      ru: "Декларации ИП, налоговая оптимизация, онлайн.",
      en: "Sole trader filings, tax optimisation, online.",
    },
    tags: ["PFA", "Freelance"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 18, experience: 9, complaints: 18 },
  },

  // ── ARCHITECTURE (new) ───────────────────────────────────────────────────
  {
    id: "nicolae-cobzac",
    name: "Nicolae Cobzac",
    title: {
      ro: "Arhitect proiectant",
      ru: "Архитектор-проектировщик",
      en: "Architectural designer",
    },
    category: "architecture",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 74,
    priceFrom: 2500,
    currency: "MDL",
    nextSlot: "Joi, 11:00",
    verified: true,
    avatar: portraits[11],
    cover: covers[0],
    bio: {
      ro: "Proiecte case, autorizații, 3D vizualizare.",
      ru: "Проекты домов, разрешения, 3D визуализация.",
      en: "House projects, permits, 3D visualisation.",
    },
    tags: ["Proiecte", "3D"],
    aiScore: 95,
    scores: { reviews: 28, profile: 20, response: 19, experience: 10, complaints: 18 },
  },
  {
    id: "ioana-sirbu",
    name: "Ioana Sîrbu",
    title: { ro: "Designer interior", ru: "Дизайнер интерьера", en: "Interior designer" },
    category: "architecture",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 112,
    priceFrom: 2000,
    currency: "MDL",
    nextSlot: "Vineri, 10:00",
    verified: true,
    avatar: portraits[2],
    cover: covers[1],
    bio: {
      ro: "Design interior complet, 3D randare, supraveghere.",
      ru: "Полный дизайн интерьера, 3D, авторский надзор.",
      en: "Full interior design, 3D renders, supervision.",
    },
    tags: ["Interior", "Randare"],
    aiScore: 96,
    scores: { reviews: 29, profile: 20, response: 19, experience: 10, complaints: 18 },
  },

  // ── CHILDCARE (new) ──────────────────────────────────────────────────────
  {
    id: "daria-popovici",
    name: "Daria Popovici",
    title: { ro: "Bonă calificată", ru: "Квалифицированная няня", en: "Qualified nanny" },
    category: "childcare",
    city: "Chișinău, Buiucani",
    rating: 4.9,
    reviewCount: 89,
    priceFrom: 150,
    currency: "MDL",
    nextSlot: "Luni, 08:00",
    verified: true,
    avatar: portraits[9],
    cover: covers[2],
    bio: {
      ro: "Îngrijire copii 0-6 ani, metode Montessori.",
      ru: "Уход за детьми 0-6 лет, метод Монтессори.",
      en: "0-6 year care, Montessori methods.",
    },
    tags: ["Bonă", "Montessori"],
    aiScore: 93,
    scores: { reviews: 28, profile: 19, response: 19, experience: 9, complaints: 18 },
  },
  {
    id: "valentina-cioban",
    name: "Valentina Cioban",
    title: { ro: "Educator preșcolar", ru: "Воспитатель дошкольников", en: "Preschool educator" },
    category: "childcare",
    city: "Chișinău, Botanica",
    rating: 4.8,
    reviewCount: 127,
    priceFrom: 180,
    currency: "MDL",
    nextSlot: "Marți, 09:00",
    verified: true,
    avatar: portraits[4],
    cover: covers[0],
    bio: {
      ro: "Jocuri educative, desen, pregătire grădiniță.",
      ru: "Развивающие игры, рисование, подготовка к садику.",
      en: "Educational games, drawing, kindergarten prep.",
    },
    tags: ["Grădiniță", "Educație"],
    aiScore: 91,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 18 },
  },

  // ── SECURITY (new) ───────────────────────────────────────────────────────
  {
    id: "igor-stratan",
    name: "Igor Stratan",
    title: {
      ro: "Specialist sisteme securitate",
      ru: "Специалист по системам безопасности",
      en: "Security systems specialist",
    },
    category: "security",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 134,
    priceFrom: 600,
    currency: "MDL",
    nextSlot: "Joi, 10:00",
    verified: true,
    avatar: portraits[6],
    cover: covers[1],
    bio: {
      ro: "CCTV, alarme, control acces, case inteligente.",
      ru: "CCTV, сигнализации, контроль доступа, умный дом.",
      en: "CCTV, alarms, access control, smart home.",
    },
    tags: ["CCTV", "Smart Home"],
    aiScore: 92,
    scores: { reviews: 27, profile: 19, response: 19, experience: 9, complaints: 18 },
  },

  // ── MOVING (new) ─────────────────────────────────────────────────────────
  {
    id: "valeriu-harea",
    name: "Valeriu Harea",
    title: {
      ro: "Servicii mutări & transport",
      ru: "Переезды и грузоперевозки",
      en: "Moving & transport services",
    },
    category: "moving",
    city: "Chișinău, Ciocana",
    rating: 4.7,
    reviewCount: 298,
    priceFrom: 400,
    currency: "MDL",
    nextSlot: "Sâmbătă, 08:00",
    verified: true,
    avatar: portraits[0],
    cover: covers[2],
    bio: {
      ro: "Mutări apartamente, birouri, ambalare inclusă.",
      ru: "Переезды квартир и офисов, упаковка включена.",
      en: "Flat & office moves, packing included.",
    },
    tags: ["Mutare", "Transport"],
    aiScore: 88,
    scores: { reviews: 26, profile: 17, response: 19, experience: 8, complaints: 18 },
  },
  {
    id: "ion-bordian",
    name: "Ion Bordian",
    title: {
      ro: "Curier & livrare marfă",
      ru: "Курьер и доставка грузов",
      en: "Courier & freight delivery",
    },
    category: "moving",
    city: "Chișinău, Botanica",
    rating: 4.6,
    reviewCount: 512,
    priceFrom: 80,
    currency: "MDL",
    nextSlot: "Astăzi, 14:00",
    verified: true,
    avatar: portraits[1],
    cover: covers[0],
    bio: {
      ro: "Livrare în zi, marfă ușoară și voluminoasă.",
      ru: "Доставка в день заказа, малые и крупные грузы.",
      en: "Same-day delivery, light & bulky freight.",
    },
    tags: ["Curier", "Livrare"],
    aiScore: 85,
    scores: { reviews: 24, profile: 16, response: 20, experience: 8, complaints: 17 },
  },

  // ── MASSAGE (new) ────────────────────────────────────────────────────────
  {
    id: "galina-stratan",
    name: "Galina Stratan",
    title: {
      ro: "Maseur terapeutic",
      ru: "Терапевтический массажист",
      en: "Therapeutic massage therapist",
    },
    category: "massage",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 231,
    priceFrom: 350,
    currency: "MDL",
    nextSlot: "Joi, 16:00",
    verified: true,
    avatar: portraits[3],
    cover: covers[1],
    bio: {
      ro: "Masaj terapeutic, relaxare, anticelulitic.",
      ru: "Терапевтический, релаксирующий, антицеллюлитный массаж.",
      en: "Therapeutic, relaxation & anti-cellulite massage.",
    },
    tags: ["Terapeutic", "Relaxare"],
    aiScore: 93,
    scores: { reviews: 28, profile: 19, response: 19, experience: 9, complaints: 18 },
  },
  {
    id: "dumitru-plugaru",
    name: "Dumitru Plugaru",
    title: { ro: "Maseur sportiv", ru: "Спортивный массажист", en: "Sports massage therapist" },
    category: "massage",
    city: "Chișinău, Râșcani",
    rating: 4.8,
    reviewCount: 147,
    priceFrom: 400,
    currency: "MDL",
    nextSlot: "Luni, 19:00",
    verified: true,
    avatar: portraits[10],
    cover: covers[2],
    bio: {
      ro: "Recuperare sportivă, masaj profund, stretching.",
      ru: "Спортивное восстановление, глубокий массаж, стретчинг.",
      en: "Sports recovery, deep tissue, stretching.",
    },
    tags: ["Sport", "Recuperare"],
    aiScore: 91,
    scores: { reviews: 27, profile: 18, response: 18, experience: 9, complaints: 19 },
  },

  // ── GARDENING (new) ──────────────────────────────────────────────────────
  {
    id: "vasile-luca",
    name: "Vasile Luca",
    title: { ro: "Peisagist & grădinar", ru: "Ландшафтный дизайнер", en: "Landscape gardener" },
    category: "gardening",
    city: "Chișinău, Buiucani",
    rating: 4.7,
    reviewCount: 104,
    priceFrom: 300,
    currency: "MDL",
    nextSlot: "Sâmbătă, 08:00",
    verified: true,
    avatar: portraits[5],
    cover: covers[0],
    bio: {
      ro: "Amenajare grădini, gazon, irigare automată.",
      ru: "Озеленение, газон, автополив.",
      en: "Garden design, lawn, automatic irrigation.",
    },
    tags: ["Grădini", "Gazon"],
    aiScore: 89,
    scores: { reviews: 26, profile: 18, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "lidia-cucos",
    name: "Lidia Cucoș",
    title: {
      ro: "Specialist plante de interior",
      ru: "Специалист по комнатным растениям",
      en: "Indoor plants specialist",
    },
    category: "gardening",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 78,
    priceFrom: 200,
    currency: "MDL",
    nextSlot: "Miercuri, 11:00",
    verified: true,
    avatar: portraits[8],
    cover: covers[1],
    bio: {
      ro: "Consultanță, replantare, soluții pentru birouri.",
      ru: "Консультации, пересадка, озеленение офисов.",
      en: "Consulting, repotting, office greening.",
    },
    tags: ["Interior", "Plante"],
    aiScore: 88,
    scores: { reviews: 26, profile: 18, response: 18, experience: 8, complaints: 18 },
  },

  // ── MUSIC (new) ──────────────────────────────────────────────────────────
  {
    id: "eugen-cojocaru",
    name: "Eugen Cojocaru",
    title: {
      ro: "Profesor chitară & ukulele",
      ru: "Преподаватель гитары и укулеле",
      en: "Guitar & ukulele teacher",
    },
    category: "music",
    city: "Chișinău, Botanica",
    rating: 4.8,
    reviewCount: 112,
    priceFrom: 200,
    currency: "MDL",
    nextSlot: "Marți, 17:00",
    verified: true,
    avatar: portraits[6],
    cover: covers[2],
    bio: {
      ro: "Începători și avansați, rock, pop, clasic.",
      ru: "Новички и продвинутые, рок, поп, классика.",
      en: "Beginners to advanced, rock, pop, classical.",
    },
    tags: ["Chitară", "Ukulele"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "silvia-anton",
    name: "Silvia Anton",
    title: { ro: "Profesor canto", ru: "Преподаватель вокала", en: "Singing teacher" },
    category: "music",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 89,
    priceFrom: 250,
    currency: "MDL",
    nextSlot: "Joi, 16:00",
    verified: true,
    avatar: portraits[2],
    cover: covers[0],
    bio: {
      ro: "Clasic, pop și jazz vocal, de la 6 ani.",
      ru: "Классический, поп и джаз вокал, с 6 лет.",
      en: "Classical, pop & jazz singing, from age 6.",
    },
    tags: ["Canto", "Vocal"],
    aiScore: 93,
    scores: { reviews: 28, profile: 19, response: 19, experience: 9, complaints: 18 },
  },

  // ── COOKING (new) ────────────────────────────────────────────────────────
  {
    id: "tudor-filip",
    name: "Tudor Filip",
    title: { ro: "Bucătar la domiciliu", ru: "Повар на дому", en: "Private chef" },
    category: "cooking",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 143,
    priceFrom: 1500,
    currency: "MDL",
    nextSlot: "Sâmbătă, 12:00",
    verified: true,
    avatar: portraits[11],
    cover: covers[1],
    bio: {
      ro: "Cine private, petreceri mici, meniuri personalizate.",
      ru: "Частные ужины, вечеринки, персональное меню.",
      en: "Private dinners, small parties, custom menus.",
    },
    tags: ["Chef", "Privat"],
    aiScore: 94,
    scores: { reviews: 28, profile: 20, response: 19, experience: 9, complaints: 18 },
  },
  {
    id: "elena-rusnac",
    name: "Elena Rusnac",
    title: { ro: "Profesor de gătit", ru: "Преподаватель кулинарии", en: "Cooking teacher" },
    category: "cooking",
    city: "Chișinău, Buiucani",
    rating: 4.7,
    reviewCount: 64,
    priceFrom: 400,
    currency: "MDL",
    nextSlot: "Duminică, 11:00",
    verified: true,
    avatar: portraits[7],
    cover: covers[2],
    bio: {
      ro: "Cursuri gătit acasă sau online, bucătărie italiană.",
      ru: "Кулинарные курсы дома или онлайн, итальянская кухня.",
      en: "Cooking classes at home or online, Italian cuisine.",
    },
    tags: ["Cursuri", "Italian"],
    aiScore: 88,
    scores: { reviews: 26, profile: 17, response: 18, experience: 9, complaints: 18 },
  },

  // ── TATTOO (new) ─────────────────────────────────────────────────────────
  {
    id: "stefan-gortolomei",
    name: "Ștefan Gortolomei",
    title: {
      ro: "Tatuator profesionist",
      ru: "Профессиональный тату-мастер",
      en: "Professional tattoo artist",
    },
    category: "tattoo",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 176,
    priceFrom: 700,
    currency: "MDL",
    nextSlot: "Vineri, 14:00",
    verified: true,
    avatar: portraits[5],
    cover: covers[0],
    bio: {
      ro: "Fine line, realism, geometric. Studio steril.",
      ru: "Файн-лайн, реализм, геометрика. Стерильная студия.",
      en: "Fine line, realism, geometric. Sterile studio.",
    },
    tags: ["Fine Line", "Realism"],
    aiScore: 95,
    scores: { reviews: 29, profile: 20, response: 18, experience: 10, complaints: 18 },
  },
  {
    id: "mia-cazacu",
    name: "Mia Cazacu",
    title: { ro: "Specialist piercing", ru: "Мастер пирсинга", en: "Piercing specialist" },
    category: "tattoo",
    city: "Chișinău, Botanica",
    rating: 4.8,
    reviewCount: 98,
    priceFrom: 300,
    currency: "MDL",
    nextSlot: "Mâine, 13:00",
    verified: true,
    avatar: portraits[4],
    cover: covers[1],
    bio: {
      ro: "Piercing corporal, bijuterii titan G23.",
      ru: "Пирсинг тела, украшения из титана G23.",
      en: "Body piercing, G23 titanium jewellery.",
    },
    tags: ["Piercing", "Titan"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 18, experience: 9, complaints: 18 },
  },

  // ── SOLAR & ENERGY (new) ─────────────────────────────────────────────────
  {
    id: "petru-cimpoies",
    name: "Petru Cimpoeș",
    title: {
      ro: "Specialist panouri solare",
      ru: "Специалист по солнечным панелям",
      en: "Solar panels specialist",
    },
    category: "energy",
    city: "Chișinău, Buiucani",
    rating: 4.8,
    reviewCount: 87,
    priceFrom: 500,
    currency: "MDL",
    nextSlot: "Joi, 09:00",
    verified: true,
    avatar: portraits[0],
    cover: covers[2],
    bio: {
      ro: "Proiectare, instalare, integrare rețea panouri solare.",
      ru: "Проектирование, монтаж и подключение солнечных панелей.",
      en: "Design, installation & grid integration of solar panels.",
    },
    tags: ["Solar", "Energie verde"],
    aiScore: 91,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 18 },
  },

  // ── ACCOUNTING extra ──────────────────────────────────────────────────────
  {
    id: "lilia-bejan",
    name: "Lilia Bejan",
    title: {
      ro: "Expert contabil & audit",
      ru: "Эксперт-бухгалтер и аудитор",
      en: "Expert accountant & auditor",
    },
    category: "accounting",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 111,
    priceFrom: 1000,
    currency: "MDL",
    nextSlot: "Luni, 10:00",
    verified: true,
    avatar: portraits[3],
    cover: covers[0],
    bio: {
      ro: "Audit intern, IFRS, raportări consolidate.",
      ru: "Внутренний аудит, МСФО, консолидированная отчётность.",
      en: "Internal audit, IFRS, consolidated reporting.",
    },
    tags: ["Audit", "IFRS"],
    aiScore: 94,
    scores: { reviews: 28, profile: 20, response: 18, experience: 10, complaints: 18 },
  },

  // ── DENTISTRY extra ──────────────────────────────────────────────────────
  {
    id: "tudor-macovei",
    name: "Dr. Tudor Macovei",
    title: { ro: "Ortodont", ru: "Ортодонт", en: "Orthodontist" },
    category: "health",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 243,
    priceFrom: 1500,
    currency: "MDL",
    nextSlot: "Miercuri, 11:00",
    verified: true,
    avatar: portraits[1],
    cover: covers[1],
    bio: {
      ro: "Aparat dentar metalic, ceramic și Invisalign.",
      ru: "Металлические, керамические брекеты и Invisalign.",
      en: "Metal, ceramic braces & Invisalign.",
    },
    tags: ["Ortodonție", "Invisalign"],
    aiScore: 95,
    scores: { reviews: 29, profile: 20, response: 18, experience: 10, complaints: 18 },
  },
  {
    id: "olga-sandu",
    name: "Dr. Olga Sandu",
    title: { ro: "Stomatolog pediatric", ru: "Детский стоматолог", en: "Paediatric dentist" },
    category: "health",
    city: "Chișinău, Botanica",
    rating: 4.9,
    reviewCount: 189,
    priceFrom: 700,
    currency: "MDL",
    nextSlot: "Vineri, 09:00",
    verified: true,
    avatar: portraits[9],
    cover: covers[2],
    bio: {
      ro: "Stomatologie copii, abordare blândă, fără frică.",
      ru: "Детская стоматология, без страха.",
      en: "Child dentistry, gentle & fear-free approach.",
    },
    tags: ["Copii", "Fără durere"],
    aiScore: 96,
    scores: { reviews: 29, profile: 20, response: 19, experience: 10, complaints: 18 },
  },

  // ── HR & RECRUITMENT (new) ───────────────────────────────────────────────
  {
    id: "maria-ursu",
    name: "Maria Ursu",
    title: { ro: "Recrutor IT", ru: "IT-рекрутер", en: "IT recruiter" },
    category: "hr",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 56,
    priceFrom: 1500,
    currency: "MDL",
    nextSlot: "Marți, 10:00",
    verified: true,
    avatar: portraits[2],
    cover: covers[0],
    bio: {
      ro: "Recrutare IT, screening tehnic, headhunting.",
      ru: "IT-рекрутинг, технический скрининг, хэдхантинг.",
      en: "IT recruitment, technical screening, headhunting.",
    },
    tags: ["IT", "Headhunting"],
    aiScore: 91,
    scores: { reviews: 27, profile: 19, response: 18, experience: 9, complaints: 18 },
  },
  {
    id: "carmen-boicu",
    name: "Carmen Boicu",
    title: {
      ro: "Coach carieră & CV",
      ru: "Карьерный коуч и резюме",
      en: "Career coach & CV writer",
    },
    category: "hr",
    city: "Chișinău, Râșcani",
    rating: 4.7,
    reviewCount: 134,
    priceFrom: 400,
    currency: "MDL",
    nextSlot: "Joi, 15:00",
    verified: true,
    avatar: portraits[7],
    cover: covers[1],
    bio: {
      ro: "CV profesional, LinkedIn, pregătire interviuri.",
      ru: "Профессиональное резюме, LinkedIn, подготовка к собеседованиям.",
      en: "Professional CV, LinkedIn, interview prep.",
    },
    tags: ["CV", "LinkedIn"],
    aiScore: 89,
    scores: { reviews: 26, profile: 18, response: 18, experience: 9, complaints: 18 },
  },

  // ── MARKETING (new) ──────────────────────────────────────────────────────
  {
    id: "natalia-bostan",
    name: "Natalia Bostan",
    title: {
      ro: "Specialist social media",
      ru: "Специалист по социальным сетям",
      en: "Social media specialist",
    },
    category: "marketing",
    city: "Chișinău, Centru",
    rating: 4.8,
    reviewCount: 167,
    priceFrom: 600,
    currency: "MDL",
    nextSlot: "Luni, 09:00",
    verified: true,
    avatar: portraits[4],
    cover: covers[2],
    bio: {
      ro: "Instagram, TikTok, Facebook Ads, content.",
      ru: "Instagram, TikTok, Facebook Ads, контент.",
      en: "Instagram, TikTok, Facebook Ads, content.",
    },
    tags: ["Instagram", "TikTok"],
    aiScore: 92,
    scores: { reviews: 27, profile: 19, response: 19, experience: 9, complaints: 18 },
  },
  {
    id: "daniela-cernei",
    name: "Daniela Cernei",
    title: {
      ro: "Copywriter & content creator",
      ru: "Копирайтер и контент-криейтор",
      en: "Copywriter & content creator",
    },
    category: "marketing",
    city: "Chișinău, Buiucani",
    rating: 4.8,
    reviewCount: 91,
    priceFrom: 350,
    currency: "MDL",
    nextSlot: "Miercuri, 10:00",
    verified: true,
    avatar: portraits[8],
    cover: covers[0],
    bio: {
      ro: "Texte vânzări, bloguri, emailuri marketing.",
      ru: "Продающие тексты, блоги, email-маркетинг.",
      en: "Sales copy, blogs, email marketing.",
    },
    tags: ["Copywriting", "Email"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 19, experience: 9, complaints: 17 },
  },
  {
    id: "victor-gavriliuc",
    name: "Victor Gavriliuc",
    title: {
      ro: "Specialist Google & Meta Ads",
      ru: "Специалист Google и Meta Ads",
      en: "Google & Meta Ads specialist",
    },
    category: "marketing",
    city: "Chișinău, Centru",
    rating: 4.9,
    reviewCount: 78,
    priceFrom: 800,
    currency: "MDL",
    nextSlot: "Joi, 11:00",
    verified: true,
    avatar: portraits[11],
    cover: covers[1],
    bio: {
      ro: "Campanii plătite, ROAS optimizat, raportare.",
      ru: "Платные кампании, оптимизация ROAS, отчётность.",
      en: "Paid campaigns, ROAS optimisation, reporting.",
    },
    tags: ["Google Ads", "Meta"],
    aiScore: 94,
    scores: { reviews: 28, profile: 20, response: 19, experience: 9, complaints: 18 },
  },

  // ── SPORT COACHING (new) ─────────────────────────────────────────────────
  {
    id: "andrei-filip",
    name: "Andrei Filip",
    title: { ro: "Antrenor fotbal", ru: "Тренер по футболу", en: "Football coach" },
    category: "sport",
    city: "Chișinău, Ciocana",
    rating: 4.7,
    reviewCount: 98,
    priceFrom: 200,
    currency: "MDL",
    nextSlot: "Sâmbătă, 10:00",
    verified: true,
    avatar: portraits[6],
    cover: covers[2],
    bio: {
      ro: "Antrenament individual și grup, copii & adulți.",
      ru: "Индивидуальные и групповые тренировки, дети и взрослые.",
      en: "Individual & group sessions, children & adults.",
    },
    tags: ["Fotbal", "Copii"],
    aiScore: 87,
    scores: { reviews: 26, profile: 17, response: 18, experience: 9, complaints: 17 },
  },
  {
    id: "marina-cebotari",
    name: "Marina Cebotari",
    title: { ro: "Antrenor tenis de câmp", ru: "Тренер по теннису", en: "Tennis coach" },
    category: "sport",
    city: "Chișinău, Botanica",
    rating: 4.8,
    reviewCount: 76,
    priceFrom: 350,
    currency: "MDL",
    nextSlot: "Duminică, 09:00",
    verified: true,
    avatar: portraits[3],
    cover: covers[0],
    bio: {
      ro: "Tenis de câmp, copii și adulți, nivel orice.",
      ru: "Большой теннис, дети и взрослые, любой уровень.",
      en: "Tennis, children & adults, all levels.",
    },
    tags: ["Tenis", "Copii"],
    aiScore: 90,
    scores: { reviews: 27, profile: 18, response: 18, experience: 9, complaints: 18 },
  },

  // ── INSURANCE (new) ──────────────────────────────────────────────────────
  {
    id: "mihail-sclifos",
    name: "Mihail Sclifos",
    title: { ro: "Broker asigurări", ru: "Страховой брокер", en: "Insurance broker" },
    category: "insurance",
    city: "Chișinău, Centru",
    rating: 4.7,
    reviewCount: 143,
    priceFrom: 0,
    currency: "MDL",
    nextSlot: "Marți, 11:00",
    verified: true,
    avatar: portraits[10],
    cover: covers[1],
    bio: {
      ro: "Asigurare auto, viață, medicală, imobil.",
      ru: "Авто, жизнь, медицина, имущество.",
      en: "Car, life, health & property insurance.",
    },
    tags: ["Auto", "Viață"],
    aiScore: 88,
    scores: { reviews: 26, profile: 17, response: 18, experience: 9, complaints: 18 },
  },
];

export function getProvider(id: string) {
  return providers.find((p) => p.id === id);
}
